#!/usr/bin/env python3
"""
Stitch together audio files generated by convert_manuscript.py into a single audiobook.
Files are combined in order (chunk_XX_section_YY.mp3) with 300ms delay between chunks/sections.
"""

import os
import re
import argparse
from pathlib import Path
from pydub import AudioSegment
import logging
from tqdm import tqdm


# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('audiobook_stitching.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


def natural_sort_key(filename):
    """
    Generate a sort key for natural sorting of filenames with numbers.
    Converts chunk_02_section_15.mp3 -> [2, 15] for proper numeric sorting.
    """
    # Extract chunk and section numbers
    match = re.search(r'chunk_(\d+)_section_(\d+)', filename)
    if match:
        chunk_num = int(match.group(1))
        section_num = int(match.group(2))
        return (chunk_num, section_num)
    return (0, 0)


def get_audio_files(directory):
    """
    Get all MP3 files from the directory that match the pattern chunk_XX_section_YY.mp3
    and sort them in the correct order.

    Args:
        directory: Path to directory containing audio files

    Returns:
        List of sorted file paths
    """
    audio_dir = Path(directory)

    if not audio_dir.exists():
        raise FileNotFoundError(f"Directory not found: {directory}")

    # Find all MP3 files matching the pattern
    pattern = re.compile(r'^chunk_\d+_section_\d+\.mp3$')
    audio_files = [
        f for f in audio_dir.iterdir()
        if f.is_file() and pattern.match(f.name)
    ]

    if not audio_files:
        raise ValueError(f"No audio files matching pattern 'chunk_XX_section_YY.mp3' found in {directory}")

    # Sort files naturally by chunk and section numbers
    audio_files.sort(key=lambda f: natural_sort_key(f.name))

    return audio_files


def stitch_audiobook(input_dir, output_path, delay_ms=300, show_progress=True):
    """
    Stitch audio files together into a single audiobook file.

    Args:
        input_dir: Directory containing the audio chunk files
        output_path: Path where the final audiobook will be saved
        delay_ms: Delay in milliseconds between audio chunks (default: 300)
        show_progress: Whether to show progress bar (default: True)

    Returns:
        Dictionary with statistics about the stitching process
    """
    logger.info(f"Starting audiobook stitching from: {input_dir}")
    logger.info(f"Output file: {output_path}")
    logger.info(f"Delay between chunks: {delay_ms}ms")

    # Get all audio files in correct order
    audio_files = get_audio_files(input_dir)
    logger.info(f"Found {len(audio_files)} audio files to stitch")

    print(f"\n{'='*70}")
    print("Audiobook Stitching")
    print(f"{'='*70}")
    print(f"Input directory: {input_dir}")
    print(f"Output file: {output_path}")
    print(f"Files to process: {len(audio_files)}")
    print(f"Delay between chunks: {delay_ms}ms")
    print(f"{'='*70}\n")

    # Initialize empty audio segment
    combined = AudioSegment.empty()
    silence = AudioSegment.silent(duration=delay_ms)

    # Process each file with progress bar
    iterator = tqdm(audio_files, desc="Stitching audio files", unit="file") if show_progress else audio_files

    for idx, audio_file in enumerate(iterator):
        try:
            # Load the audio file
            logger.debug(f"Loading file {idx + 1}/{len(audio_files)}: {audio_file.name}")
            chunk = AudioSegment.from_mp3(str(audio_file))

            # Add the audio chunk
            combined += chunk

            # Add silence delay between chunks (except after the last file)
            if idx < len(audio_files) - 1:
                combined += silence

        except Exception as e:
            logger.error(f"Error processing file {audio_file.name}: {e}")
            print(f"\nError processing {audio_file.name}: {e}")
            print("Skipping this file and continuing...")
            continue

    # Export the final audiobook
    print("\nExporting final audiobook...")
    logger.info("Exporting final audiobook")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Determine output format from file extension
    output_format = output_path.suffix[1:].lower()  # Remove the dot
    if output_format not in ['mp3', 'wav', 'ogg', 'flac']:
        output_format = 'mp3'
        output_path = output_path.with_suffix('.mp3')
        logger.warning(f"Unsupported format, defaulting to MP3")

    # Export with high quality settings
    export_params = {
        'format': output_format,
        'parameters': ["-q:a", "0"]  # Highest quality
    }

    if output_format == 'mp3':
        export_params['bitrate'] = '192k'

    combined.export(str(output_path), **export_params)

    # Calculate statistics
    file_size_mb = output_path.stat().st_size / (1024 * 1024)
    duration_seconds = len(combined) / 1000
    duration_minutes = duration_seconds / 60
    duration_hours = duration_minutes / 60

    stats = {
        'num_files': len(audio_files),
        'output_path': str(output_path),
        'file_size_mb': file_size_mb,
        'duration_seconds': duration_seconds,
        'duration_minutes': duration_minutes,
        'duration_hours': duration_hours
    }

    print(f"\n{'='*70}")
    print("Stitching Complete!")
    print(f"{'='*70}")
    print(f"Output file: {output_path}")
    print(f"Files stitched: {len(audio_files)}")
    print(f"File size: {file_size_mb:.1f} MB")
    print(f"Total duration: {duration_hours:.2f} hours ({duration_minutes:.1f} minutes)")
    print(f"{'='*70}\n")

    logger.info(f"Audiobook stitching complete: {stats}")

    return stats


def main():
    parser = argparse.ArgumentParser(
        description='Stitch audio files generated by convert_manuscript.py into a single audiobook',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage with default settings (300ms delay)
  python stitch_audiobook.py /path/to/audio/files

  # Specify output file and custom delay
  python stitch_audiobook.py /path/to/audio/files -o my_audiobook.mp3 -d 500

  # Use different output format
  python stitch_audiobook.py /path/to/audio/files -o audiobook.flac
        """
    )

    parser.add_argument(
        'input_dir',
        type=str,
        help='Directory containing the audio chunk files (chunk_XX_section_YY.mp3)'
    )

    parser.add_argument(
        '-o', '--output',
        type=str,
        default=None,
        help='Output file path (default: <input_dir>/complete_audiobook.mp3)'
    )

    parser.add_argument(
        '-d', '--delay',
        type=int,
        default=300,
        help='Delay in milliseconds between audio chunks (default: 300)'
    )

    parser.add_argument(
        '--no-progress',
        action='store_true',
        help='Disable progress bar'
    )

    args = parser.parse_args()

    # Resolve input directory
    input_dir = Path(args.input_dir).resolve()

    # Determine output path
    if args.output:
        output_path = Path(args.output).resolve()
    else:
        output_path = input_dir / 'complete_audiobook.mp3'

    try:
        stats = stitch_audiobook(
            input_dir=input_dir,
            output_path=output_path,
            delay_ms=args.delay,
            show_progress=not args.no_progress
        )

        print(f"✓ Success! Audiobook saved to: {stats['output_path']}")

    except FileNotFoundError as e:
        logger.error(f"File/directory not found: {e}")
        print(f"\nError: {e}")
        return 1
    except ValueError as e:
        logger.error(f"Invalid input: {e}")
        print(f"\nError: {e}")
        return 1
    except Exception as e:
        logger.error(f"Unexpected error: {e}", exc_info=True)
        print(f"\nUnexpected error: {e}")
        print("Check audiobook_stitching.log for details")
        return 1

    return 0


if __name__ == "__main__":
    exit(main())